export enum PurposeType {
  REGISTRATION = 'REGISTRATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  NEW_PHONE_VERIFICATION = 'NEW_PHONE_VERIFICATION',
  NEW_VOLUNTEER_REQUEST = 'NEW_VOLUNTEER_REQUEST',
  PHONE_NUMBER_UPDATE = 'PHONE_NUMBER_UPDATE',
}
